### ISSUE TITLE
Update existing dat file

### ISSUE THREAD

**Issue by cormite** [PotcFdk/agedu#1]
Maybe this feature is already present but it is not yet fully clear to me.

Is it possible to update an existing index file? Let's say you want to identify the data that hasn't been used in a large amount of data (dozens of TBs and up) and identify this periodically (i.e., weekly/monthly to identify folders not used in the last 3-6 months) for archiving purposes. The first creation of index file will take quite some time, would it be possible to just update it instead of running it again from the beginning?

Thanks!

**Comment by PotcFdk** [comment]
Hi, I'm not the maintainer of the agedu project; this is only a GitHub mirror.
Upstream is at https://www.chiark.greenend.org.uk/~sgtatham/agedu/

As for your question, I'm not 100 % sure, but I suspect that feature does not exist.
